version: 2
jobs:
    one:
        docker:
            - image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run: echo "A first hello"
            - run: sleep 25
    two:
        docker:
            - image: circleci/ruby:2.4.1
        steps:
            - checkout
            - run: echo "second greeting is second"
            - run: sleep 15
    nodeone:
        docker:
            - image: circleci/node:12.8.0
        working_directory: ~/repo
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "package.json"}}
                    - v1-dependencies-
            - run: npm install
            - save_cache:
                paths:
                    - node_modules
                key: v1-dependencies-{{ checksum "package.json"}}
            - run: npm run test
workflows:
    version: 2
    nodejob:
        jobs:
            - nodeone
             